fullnameOverride: simple-db
postgresqlUsername: user
postgresqlPassword: strong_passwd
postgresqlDatabase: users

service:
  type: NodePort
  port: 5432

persistence:
  enabled: true
  size: 100Mi

resources:
  requests:
    memory: 256Mi
    cpu: 250m

